// Generates the wallee presentation tiles in dist/tiles/svg from the untouched
// source files listed in registry/tile-sources.json.
//
// Tile geometry (registry/brands.json → presentation.tile):
//   120 × 80 canvas, rounded corners
//   1 px white at the absolute outer edge
//   2 px wallee turquoise #11D9CC directly inside
//   then the logo field (white), holding the source artwork unchanged
//
// Source artwork is embedded verbatim: no path, colour or aspect-ratio change.
// Identical inputs give byte-identical output.

import fs from "node:fs";
import path from "node:path";

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const brands = JSON.parse(fs.readFileSync(path.join(root, "registry/brands.json"), "utf8"));
const map = JSON.parse(fs.readFileSync(path.join(root, "registry/tile-sources.json"), "utf8")).tiles;
const t = brands.presentation.tile;

const W = 120, H = 80;
const OUT = t.outerWhitePx;          // 1
const FRAME = t.framePx;             // 2
const IN = OUT + FRAME;              // logo field starts here (3)
const COLOR = t.frameColor;          // #11D9CC
const R = 5;                         // outer corner radius
const field = { x: IN, y: IN, w: W - 2 * IN, h: H - 2 * IN, r: R - IN };

const UNSAFE = /<script|\son[a-z]+\s*=|<foreignObject|<image|href\s*=\s*"(?!#)|@import|url\((?!#)/i;

const names = Object.fromEntries(brands.brands.map(b => [b.id, b.name]));
const esc = s => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

function frame(id) {
  return [
    `<svg width="${W}" height="${H}" viewBox="0 0 ${W} ${H}" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">`,
    `<!-- wallee presentation tile for "${id}". Generated by scripts/build-tiles.mjs; source artwork embedded unchanged. -->`,
    `<rect width="${W}" height="${H}" rx="${R}" fill="#FFFFFF"/>`,
    `<rect x="${OUT}" y="${OUT}" width="${W - 2 * OUT}" height="${H - 2 * OUT}" rx="${R - OUT}" fill="${COLOR}"/>`,
    `<rect x="${field.x}" y="${field.y}" width="${field.w}" height="${field.h}" rx="${field.r}" fill="#FFFFFF"/>`,
  ];
}

function readSvg(file) {
  const raw = fs.readFileSync(path.join(root, file), "utf8");
  if (UNSAFE.test(raw)) throw new Error(`unsafe SVG content in ${file}`);
  const open = raw.match(/<svg\b[^>]*>/);
  if (!open) throw new Error(`no <svg> root in ${file}`);
  let vb = open[0].match(/viewBox="([^"]+)"/)?.[1];
  if (!vb) {
    // Some sources only carry width/height; that is the same coordinate system.
    const w = open[0].match(/\swidth="([\d.]+)"/)?.[1];
    const h = open[0].match(/\sheight="([\d.]+)"/)?.[1];
    if (!w || !h) throw new Error(`no viewBox or size in ${file}`);
    vb = `0 0 ${w} ${h}`;
  }
  const inner = raw.slice(raw.indexOf(open[0]) + open[0].length, raw.lastIndexOf("</svg>")).trim();
  // Presentation attributes on the source root (e.g. fill="none") are inherited by
  // the artwork and must travel with it, otherwise unfilled shapes turn black.
  const keep = [...open[0].matchAll(/\s([a-zA-Z:-]+)="([^"]*)"/g)]
    .filter(([, k]) => !/^(xmlns(:.*)?|width|height|viewBox|x|y|version|id|preserveAspectRatio)$/.test(k))
    .map(([, k, v]) => ` ${k}="${v}"`).join("");
  return { viewBox: vb, inner, attrs: keep };
}

function nested(box, viewBox, inner, attrs = "") {
  return `<svg${attrs} x="${box.x}" y="${box.y}" width="${box.w}" height="${box.h}" viewBox="${viewBox}" preserveAspectRatio="xMidYMid meet">\n${inner}\n</svg>`;
}

function build(id, spec) {
  const out = frame(id);
  const body = [];
  if (spec.mode === "card") {
    // Card-format source (120 × 80): fills the logo field directly inside the frame.
    const s = readSvg(spec.source);
    body.push(nested(field, s.viewBox, s.inner, s.attrs));
  } else if (spec.mode === "mark") {
    // Free-standing wordmark: centred in the field with clearspace.
    const s = readSvg(spec.source);
    const pad = 9;
    body.push(nested({ x: field.x + pad, y: field.y + pad, w: field.w - 2 * pad, h: field.h - 2 * pad }, s.viewBox, s.inner, s.attrs));
  } else if (spec.mode === "badge") {
    // Square raster badge supplied as master: full field height, centred, pixels untouched.
    const buf = fs.readFileSync(path.join(root, spec.source));
    const size = field.h;
    const x = (W - size) / 2;
    body.push(`<image x="${x}" y="${field.y}" width="${size}" height="${size}" preserveAspectRatio="xMidYMid meet" href="data:image/png;base64,${buf.toString("base64")}"/>`);
  } else if (spec.mode === "placeholder") {
    const label = esc(names[id] ?? id);
    body.push(`<text x="60" y="37" text-anchor="middle" font-family="Roboto,Arial,sans-serif" font-size="9" font-weight="700" fill="#1B2D52">${label}</text>`);
    body.push(`<text x="60" y="50" text-anchor="middle" font-family="Roboto,Arial,sans-serif" font-size="5.5" fill="#666666">OFFICIAL MASTER PENDING</text>`);
  } else {
    throw new Error(`unknown mode ${spec.mode} for ${id}`);
  }
  out.push(...body, `</svg>`);
  return out.join("\n") + "\n";
}

const dir = path.join(root, "dist/tiles/svg");
fs.mkdirSync(dir, { recursive: true });
let n = 0;
for (const id of Object.keys(map).sort()) {
  fs.writeFileSync(path.join(dir, `${id}.svg`), build(id, map[id]));
  n++;
}
console.log(`Built ${n} tiles (${OUT} px white, ${FRAME} px ${COLOR}).`);
